name = "BBVV1D"
uuid = "301be7c6-8d1a-4696-95bf-87aa5c26a29f"
authors = ["Kai Partmann <kai.partmann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "1.7"
